# coding: utf-8
get_ipython().magic(u'pwd ')
get_ipython().magic(u'run MasterScript_v2.py')
get_ipython().magic(u'run MasterScript_v2.py')
homogenous_crystal(0.1, 0.1, 0.001, 2.5, 10, 1, "trial")
get_ipython().magic(u'run MasterScript_v2.py')
homogenous_crystal(0.1, 0.1, 0.001, 2.5, 10, 1, "try")
get_ipython().magic(u'pwd ')
get_ipython().magic(u'history ')
get_ipython().magic(u'pinfo history')
get_ipython().system(u'history')
get_ipython().system(u'hist')
get_ipython().system(u'history')
get_ipython().magic(u'history ')
get_ipython().magic(u'history -g')
get_ipython().magic(u'pinfo history')
get_ipython().magic(u'history -g')
get_ipython().magic(u'history')
HISTTIMEFORMAT="%d/%m/%y %T "
get_ipython().magic(u'history ')
get_ipython().magic(u'pinfo os.rename')
get_ipython().magic(u'history ')
get_ipython().magic(u'pwd ')
get_ipython().magic(u'pinfo save')
get_ipython().magic(u'pinfo save')
get_ipython().magic(u'save terminal_session')
get_ipython().magic(u"save 'terminal_session'")
get_ipython().magic(u"save 'terminal_session'")
get_ipython().magic(u'save current_session ~0/')
